blog/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d+)/comments/$', views.comment_list, name='comment_list'),
    url(r'^(?P<post_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),

    url(r'^posts\.json$', views.post_list_json),

    url(r'^api/v1/', include('blog.api')),
]

front/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^chart/', include('chart.urls', namespace='chart')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField()
    photo = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-id']

blog/forms.py
import re
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message', 'photo']

    def clean_message(self):
        message = self.cleaned_data.get('message', None)
        if message:
            if not re.search(r'[ㄱ-힣]', message):
                raise forms.ValidationError('메세지에 한글이 필요합니다.')
        return message

blog/views.py
from django.shortcuts import render, get_object_or_404, resolve_url
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from .models import Post, Comment
from django.urls import reverse_lazy
from django.http import JsonResponse, HttpResponse
from .serializers import PostSerializer
from rest_framework.renderers import JSONRenderer
from django.template.defaultfilters import truncatewords
from .forms import CommentForm

class PostListView(ListView):
    model = Post
    paginate_by=10

    def get_template_names(self):
        if self.request.is_ajax():
            return ['blog/_post_list.html']
        return ['blog/index.html']


index = PostListView.as_view(model=Post, template_name='blog/index.html', paginate_by=10)


class PostDetailView(DetailView):
    model = Post

    def render_to_response(self, context):
        if self.request.is_ajax():
            return JsonResponse({
                'title': self.object.title,
                'summary': truncatewords(self.object.content,100),
            })
        return super().render_to_response(context)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context


post_detail = PostDetailView.as_view()


post_edit = UpdateView.as_view(model=Post, fields='__all__')


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')


post_delete = PostDeleteView.as_view()

post_new = CreateView.as_view(model=Post, fields='__all__')

class CommentListView(ListView):
    model = Comment
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(post__id = self.kwargs['post_pk'])

        latest_comment_id = self.request.GET.get('latest_comment_id', None)
        if latest_comment_id:
            qs = qs.filter(id__gt = latest_comment_id)
        return qs


comment_list = CommentListView.as_view()

class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=self.kwargs['post_pk'])
        response = super().form_valid(form)

        if self.request.is_ajax():
            return render(self.request, 'blog/_comment.html', {
                'comment': comment,
            })

        return response

    def get_success_url(self):
        return resolve_url(self.object.post)

    def get_template_names(self):
        if self.request.is_ajax():
            return ['blog/_comment_form.html']
        return ['blog/comment_form.html'] 

comment_new = CommentCreateView.as_view()


class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        response = super().form_valid(form)

        if self.request.is_ajax():
            return render(self.request, 'blog/_comment.html', {
                'comment': self.object,
            })
        
        return response

    def get_success_url(self):
        return resolve_url(self.object.post)

    def get_template_names(self):
        if self.request.is_ajax():
            return ['blog/_comment_form.html']
        return ['blog/comment_form.html']


comment_edit = CommentUpdateView.as_view()


class CommentDeleteView(DeleteView):
    model = Comment
    
    def get_success_url(self):
        return resolve_url(self.object.post)


comment_delete = CommentDeleteView.as_view()

def post_list_json(request):
    qs = Post.objects.all()
    
    serializer = PostSerializer(qs, many=True)
    json_utf8_string = JSONRenderer().render(serializer.data)
    return HttpResponse(json_utf8_string, content_type='application/json; charset=utf-8')

blog/templates/blog/_comment.html
{% load thumbnail %}

<div id="comment-{{ comment.pk }}" class="media comment" data-comment-id="{{ comment.pk }}">
    {% if comment.photo %}        
        <div class="media-left">
            <a href="#">
                <img src="{% thumbnail comment.photo 100x100 crop %}" alt="" class="media-object">
            </a>
        </div>
    {% endif %}

    <div class="media-body">
        <h4 class="media-heading">Media heading</h4>
        <p>{{ comment.message }}</p>
        &dash; 
        <a href="{% url "blog:comment_edit" comment.post.pk comment.pk %}" class="modal-form-btn" data-target-id="comment-{{ comment.pk }}">
            <small>{{ comment.updated_at }}</small>
        </a>
        <a href="{% url "blog:comment_delete" comment.post.pk comment.pk %}" class="ajax-post-confirm" data-target-id="comment-{{ comment.pk }}" data-message="삭제하시겠습니까?">
            <small>삭제</small>
        </a>
    </div>
</div>

blog/templates/blog/_comment_form.html
{% load bootstrap3 %}

<form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
</form>

blog/templates/blog/_post_list.html
{% for post in post_list %}
<tr>
    <td>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }} {% if post.comment_set.count != 0 %}[{{ post.comment_set.count }}]{% endif %}
        </a>
    </td>
</tr>
{% endfor %}

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post">
                    {% csrf_token %}
                    <p class="alert alert-danger">정말 삭제하시겠습니까?</p>

                    <input type="submit" value="삭제" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "blog/_comment_form.html" %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/comment_list.html
{% for comment in comment_list %}
    {% include "blog/_comment.html" %}
{% endfor %}

<hr>
{% if is_paginated %}
    {% for page_number in paginator.page_range %}
        <a id="page-{{ page_number }}-btn" href="{% url "blog:comment_list" comment_list.first.post.pk %}?page={{ page_number }}" class="btn btn-primary">{{ page_number }}</a>
    {% endfor %}
{% endif %}

<script>
    '{% for page_number in paginator.page_range %}'
    $(document).on('click', '#page-{{ page_number }}-btn', function(e) {
        e.preventDefault();

        var url = $(this).attr('href')
        $.get(url)
        .done(function(html) {
            $('#comment-list').html(html);
            var state_obj = {};
            var url = "?page={{ page_number }}";

            history.pushState(state_obj, url);
        })
        .fail(function(xhr, textStatus, error) {
            alert('failed : ' +error );
        });

        return false;
    })
    '{% endfor %}'
</script>

blog/templates/blog/index.html
{% extends "blog/layout.html" %}

{% block extra_body %}
    <script>
        $(function() {
            var $win = $(window);
            var is_loading = false;
            var current_page = null;

            var load_more = function() {
                if (!is_loading) {

                    //var search_params = new URLSearchParams(window.location.search); // 현재 페이지의 GET인자를 가공
                    //var current_page = parseInt(search_params.get('page')) || 1; // GET인자 page를 획득하고 없으면 1을 반환
                    var next_page = (current_page || 1) + 1;
                    var next_page_url = '?page=' + next_page; // 다음 페이지를 요청하기 위한 URL생성

                    is_loading = true;

                    $.get(next_page_url).
                    done(function(html) {
                        $('#post-list tbody').append(html);
                        current_page = next_page;
                        //history.pushState({}, '', next_page_url);
                    }).
                    fail(function(xhr, textStatus, error) {
                        console.log(textStatus);
                    })
                    .always(function() {
                        console.log("always");
                        console.log(current_page);
                        is_loading = false;
                    });
                };
            }

            $win.scroll(function() {
                var diff = $(document).height() - $win.height();
                
                if (diff == parseInt($win.scrollTop()) ) {
                    load_more();
                };
            });

            $('#load-more-btn').click(load_more);

            $(document).on('click', '#post-list a', function(e){
                e.preventDefault();

                var detail_url = $(this).attr('href');

                var title = $(this).html();

                $.get(detail_url)
                .done(function(json_obj) {
                    var $modal = $('#post-modal');
                    $modal.find('.modal-title').html(json_obj.title);
                    $modal.find('.modal-body').html(json_obj.summary);
                    $modal.find('.btn-detail').attr('href', detail_url);
    
                    $modal.modal()
                })
                .fail(function(xhr, textStatus, error) {
                    alert('failed : ' + error);
                });
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-hover" id="post-list">
                    <tbody>
                        {% include "blog/_post_list.html" %}
                    </tbody>
                </table>

                <a class="btn btn-primary" id="load-more-btn">Load More</a>

                <hr>
                <a href="{% url "blog:post_new" %}" class="btn btn-primary">새 글쓰기</a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="post-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">포스팅 제목</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...<br/>
                    ...<br/>
                    ...<br/>
                    ...<br/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                    <a class="btn btn-primary btn-detail">자세히</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load static_tags %}

{% block extra_head %}
   <link rel="stylesheet" href="{% static_t "blog/style.css" %}">
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post">
                    {% csrf_token %}
                    <p class="alert alert-danger">정말 삭제하시겠습니까?</p>

                    <input type="submit" value="삭제" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block extra_body %}
<script>
    $(function() {
        $('#check-comment').click(function(e) {
            e.preventDefault();

            var comment_id = $('#comment-list .comment:first').data('comment-id');

            $.get('{% url "blog:comment_list" post.pk %}',{latest_comment_id: comment_id})
            .done(function(html) {
                $('#comment-list').prepend(html);
            })
            .fail(function(xhr, textStatus, error) {
                alert('failed : ' + error);
            });
        });

        $.get('{% url "blog:comment_list" post.pk %}')
        .done(function(html) {
            $('#comment-list').html(html);
        })
        .fail(function(xhr, textStatus, error) {
            alert('failed : ' + error);
        });        
    });
</script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>{{ post.title }}</h1>
                
                {{ post.content|linebreaks }}
                
                <hr>
                
                <a href="{% url "blog:comment_new" post.pk %}" class="modal-form-btn btn btn-primary btn-block">댓글쓰기</a>

                <a id="check-comment" href="" class="btn btn-primary btn-block">새 댓글 확인</a>
                <div id="comment-list">
                </div>
       
                <hr>
                
                <a href="{% url "blog:index" %}" class="btn btn-primary">목록</a>
                <a href="{% url "blog:post_edit" post.pk %}" class="btn btn-primary">수정</a>
                <a href="{% url "blog:post_delete" post.pk %}" class="btn btn-danger">삭제</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/temp.html
{% extends "blog/layout.html" %}

{% block extra_body %}
    <script>
        $(function() {
            var $win = $(window);
            var is_loading = false;

            $win.scroll(function() {
                var diff = $(document).height() - $win.height();
                
                if ( (!is_loading) && diff == parseInt($win.scrollTop()) ) {
                    var search_params = new URLSearchParams(window.location.search); // 현재 페이지의 GET인자를 가공
                    var current_page = parseInt(search_params.get('page')) || 1; // GET인자 page를 획득하고 없으면 1을 반환
                    var next_page_url = '?page=' + (current_page + 1); // 다음 페이지를 요청하기 위한 URL생성

                    is_loading = true;

                    $.get(next_page_url).
                    done(function(html) {
                        $('#post-list tbody').append(html);
                        //history.pushState({}, '', next_page_url);
                    }).
                    fail(function(xhr, textStatus, error) {
                        console.log(textStatus);
                    })
                    .always(function() {
                        console.log("always");
                        is_loading = false;
                    });
                };
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-hover" id="post-list">
                    <tbody>
                        {% include "blog/_post_list.html" %}
                    </tbody>
                </table>

                <hr>
                <a href="{% url "blog:post_new" %}" class="btn btn-primary">새 글쓰기</a>
            </div>
        </div>
    </div>
{% endblock content %}