blog/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d+)/comments/$', views.comment_list, name='comment_list'),
    url(r'^(?P<post_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),

    url(r'^posts\.json$', views.post_list_json),

    url(r'^api/v1/', include('blog.api')),
]

chart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^data.json$', views.data_json, name="data_json"),
]

front/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^chart/', include('chart.urls', namespace='chart')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

chart/models.py
from django.db import models

# Create your models here.

chart/views.py
from django.shortcuts import render
from .utils import get_comic_info
from django.http import JsonResponse
from chartjs.views.lines import BaseLineChartView

def index(request):
    return render(request, 'chart/index.html')

'''
def data_json(request):
    comic = get_comic_info(20853, '마음의 소리')
    
    return JsonResponse({
        'labels': [ep['title'] for ep in comic['ep_list']],
        'datasets': [{
            'label': '평점',
            'backgroundColor': 'rgba(255, 99, 132, 0.5)',
            'borderColor': 'rgba(255, 99, 132, 1)',
            'pointBackgroundColor': 'rgba(255, 99, 132, 1)',
            'pointBorderColor': '#fff',
            'data': [ep['rating'] for ep in comic['ep_list']],
        }],
    })
'''

class WebtooonChartJSONView(BaseLineChartView):
    def __init__(self):
        super().__init__()
        self.comic = get_comic_info(20853, '마음의소리')
    
    def get_labels(self):
        return [ep['title'] for ep in self.comic['ep_list']]

    def get_providers(self):
        return ['평점']

    def get_data(self):
        return [
            [ep['rating'] for ep in self.comic['ep_list']],
        ]

    def get_colors(self):
        yield (255,99,132)


data_json = WebtooonChartJSONView.as_view()

chart/templates/chart/index.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <script src="http://www.chartjs.org/dist/2.7.0/Chart.bundle.js"></script>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    </head>
    <body>
        <canvas id="canvas"></canvas>
        <script>
            $(function() {
                $.get('{% url "chart:data_json" %}')
                .done(function(chartData) {
                    var ctx = document.getElementById('canvas').getContext('2d');
                    window.chart = new Chart(ctx, {
                        type: 'line',
                        data: chartData
                    });
                })
                .fail(function(xhr, textStatus, error) {
                    alert('failed : ' + error);
                });
            })
        </script>
    </body>
</html>